### ISSUE TITLE
TranscriptionAnalyses - Count/Normalization Calculation - Broken Histogram

### ISSUE THREAD

**Issue by pblumenkamp** [ag-computational-bio/ReadXplorer#2]
**On Win10!**

Where: TranscriptionAnalyses - Read Count and Normalization Calculation - Show Histogram
Settings: Default

Histogram cannot be drawn for the results.

```
java.lang.RuntimeException: No toolkit found
	at com.sun.javafx.tk.Toolkit.getToolkit(Toolkit.java:272)
	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:267)
	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:158)
	at javafx.embed.swing.JFXPanel.lambda$initFx$1(JFXPanel.java:224)
[catch] at java.base/java.lang.Thread.run(Thread.java:832)
```

----

Product Version: ReadXplorer 2.3
Java: 14.0.1; Java HotSpot(TM) 64-Bit Server VM 14.0.1+7
Runtime: Java(TM) SE Runtime Environment 14.0.1+7
System: Windows 10 version 10.0 running on amd64; Cp1252; de_DE (readxplorer)
User directory: C:\Users\XXXX.readxplorer\dev
Cache directory: C:\Users\XXXX.readxplorer\dev\var\cache

**Comment by pblumenkamp** [comment]
![Clipboard - June 16, 2020 5_35 PM](https://user-images.githubusercontent.com/9703726/89033916-288a4100-d338-11ea-9c27-07fbb93f2687.png)
