### ISSUE TITLE
Import data - References - Add Fasta file - fas file extension not supported

### ISSUE THREAD

**Issue by pblumenkamp** [ag-computational-bio/ReadXplorer#9]
Where: Import data - References - Add fasta file
Condition: New database; Fasta is first entry
Test file: [test.fas.zip](https://github.com/ag-computational-bio/ReadXplorer/files/4793164/test.fas.zip)

During Import of fasta file, this exception was thrown:

```
java.lang.IllegalArgumentException: File is not a supported reference file type: /home/patrick/tmp/Andreas_Test/Error2/test.fas
	at htsjdk.samtools.reference.ReferenceSequenceFileFactory.lambda$getFastaExtension$0(ReferenceSequenceFileFactory.java:253)
	at java.util.Optional.orElseGet(Optional.java:267)
	at htsjdk.samtools.reference.ReferenceSequenceFileFactory.getFastaExtension(ReferenceSequenceFileFactory.java:253)
	at htsjdk.samtools.reference.ReferenceSequenceFileFactory.getDefaultDictionaryForReferenceSequence(ReferenceSequenceFileFactory.java:223)
	at htsjdk.samtools.reference.AbstractFastaSequenceFile.findSequenceDictionary(AbstractFastaSequenceFile.java:110)
	at htsjdk.samtools.reference.AbstractFastaSequenceFile.findAndLoadSequenceDictionary(AbstractFastaSequenceFile.java:86)
	at htsjdk.samtools.reference.AbstractFastaSequenceFile.lambda$new$9c19d50a$1(AbstractFastaSequenceFile.java:68)
	at htsjdk.samtools.util.Lazy.get(Lazy.java:25)
	at htsjdk.samtools.reference.AbstractFastaSequenceFile.getSequenceDictionary(AbstractFastaSequenceFile.java:140)
	at htsjdk.samtools.reference.IndexedFastaSequenceFile.getSequenceDictionary(IndexedFastaSequenceFile.java:49)
	at htsjdk.samtools.reference.AbstractIndexedFastaSequenceFile.<init>(AbstractIndexedFastaSequenceFile.java:67)
	at htsjdk.samtools.reference.IndexedFastaSequenceFile.<init>(IndexedFastaSequenceFile.java:80)
	at htsjdk.samtools.reference.IndexedFastaSequenceFile.<init>(IndexedFastaSequenceFile.java:62)
	at htsjdk.samtools.reference.IndexedFastaSequenceFile.<init>(IndexedFastaSequenceFile.java:71)
	at de.cebitec.readxplorer.databackend.SaveFileFetcherForGUI.checkRefFile(SaveFileFetcherForGUI.java:424)
	at de.cebitec.readxplorer.databackend.dataobjects.PersistentReference.checkRef(PersistentReference.java:138)
	at de.cebitec.readxplorer.databackend.dataobjects.PersistentReference.<init>(PersistentReference.java:124)
	at de.cebitec.readxplorer.databackend.dataobjects.PersistentReference.<init>(PersistentReference.java:94)
	at de.cebitec.readxplorer.databackend.dataobjects.PersistentReference.<init>(PersistentReference.java:77)
	at de.cebitec.readxplorer.databackend.connector.ProjectConnector.getReferences(ProjectConnector.java:1074)
	at de.cebitec.readxplorer.databackend.connector.ProjectConnector.getReferencesAndTracks(ProjectConnector.java:1171)
	at de.cebitec.readxplorer.dashboard.DashboardWindowTopComponent.refreshData(DashboardWindowTopComponent.java:187)
	at de.cebitec.readxplorer.dashboard.DashboardWindowTopComponent$1$1$1.run(DashboardWindowTopComponent.java:147)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:136)
[catch] at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

```

----

Product Version: ReadXplorer 2.3
Java: 1.8.0_201; Java HotSpot(TM) 64-Bit Server VM 25.201-b09
Runtime: Java(TM) SE Runtime Environment 1.8.0_201-b09
System: Linux version 4.15.0-58-generic running on amd64; UTF-8; en_US (readxplorer)
User directory: /home/patrick/.readxplorer/dev
Cache directory: /home/patrick/.readxplorer/dev/var/cache

**Comment by sjaenick** [comment]
https://github.com/ag-computational-bio/ReadXplorer/commit/bd0e95cb758629221a6fc34faa7bd804030fd26f

**Comment by sjaenick** [comment]
https://github.com/samtools/htsjdk/pull/1495

**Comment by sjaenick** [comment]
PR merged upstream, awaiting new release

**Comment by sjaenick** [comment]
https://github.com/samtools/htsjdk/issues/1515

**Comment by sjaenick** [comment]
fix released upstream, included in 2.24.0

**Comment by sjaenick** [comment]
Please verify and close.

**Comment by pblumenkamp** [comment]
**fas** file import is now working
